name: Build and push Docker image

on:
  schedule:
    - cron: '15 20 * * 0'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: docker/
        file: docker/Dockerfile
        push: true
        pull: true
        tags: |
          srfonline/github-runner:latest
